"""Empirical Leverage Index for a live baseball situation.

Leverage Index (LI) measures how much win probability can move in the current
plate appearance, normalized so an average situation is 1.0. Unlike the old
``心跳指數``, the value here is not assembled from hand-picked inning and
closeness multipliers: it is looked up from an empirical win-expectancy model.

The bundled table was generated by Greg Stoll's open-source model from
Retrosheet play-by-play data. That model calculates expected absolute changes
in win expectancy over three context-neutral outcomes (home run, hit, out) and
normalizes the result by the league-wide average. See
``scripts/build_li_table.py`` for the exact source and reproducible import.

The table is MLB-derived because a sufficiently large public CPBL historical
state table is not bundled with this project. LI is still a real, reproducible
metric, but its run environment should not be described as CPBL-calibrated.
"""

from __future__ import annotations

from dataclasses import dataclass

from .li_table import LI_TABLE
from .models import GameState


# Twice average is a conventional, legible boundary for a high-leverage plate
# appearance. The threshold remains a user preference; it is not part of LI.
DEFAULT_THRESHOLD = 2.0
WATCH_THRESHOLD = 1.5


@dataclass(frozen=True)
class Assessment:
    leverage: float
    tier: str          # "alert" | "watch" | "quiet"
    reasons: tuple[str, ...]

    @property
    def should_alert(self) -> bool:
        return self.tier == "alert"


def _runner_code(state: GameState) -> int:
    """Return the source table's one-based base occupancy bitmask."""
    return 1 + int(state.first) + 2 * int(state.second) + 4 * int(state.third)


def leverage_index(state: GameState) -> float:
    """Return pre-plate-appearance LI for ``state``.

    Stoll's table identifies the batting side as H/V and expresses run
    differential from that side's perspective. Regulation inning 9 is used
    for extras: those sparse historical states are unstable, while the ninth
    preserves the correct walk-off asymmetry. Margins beyond eight runs are
    intentionally quiet; none can meet the notification threshold in the
    well-populated portion of the source model.
    """
    batting_side = "V" if state.is_top else "H"
    inning = min(max(state.inning, 1), 9)
    outs = min(max(state.outs, 0), 2)
    run_diff = state.batting_score - state.fielding_score
    if not -8 <= run_diff <= 8:
        return 0.0

    values = LI_TABLE.get((batting_side, inning, outs, _runner_code(state)))
    if values is None:
        return 0.0
    return values[run_diff + 8]


def _reasons(state: GameState) -> tuple[str, ...]:
    reasons: list[str] = []
    if state.loaded:
        reasons.append("滿壘")
    elif state.risp:
        bases = []
        if state.third:
            bases.append("三壘")
        if state.second:
            bases.append("二壘")
        reasons.append("得點圈有人（" + "、".join(bases) + "）")
    elif state.first:
        reasons.append("一壘有人")
    reasons.append(f"{state.outs}出局")
    if state.inning >= 7:
        reasons.append(f"{state.inning}局{state.half}（終盤）")
    if state.deficit == 0:
        reasons.append("平手")
    elif state.deficit > 0:
        reasons.append(f"落後{state.deficit}分")
    else:
        reasons.append(f"領先{-state.deficit}分")
    return tuple(reasons)


def assess(state: GameState, threshold: float = DEFAULT_THRESHOLD) -> Assessment:
    """Classify a game situation on the empirical LI scale."""
    leverage = round(leverage_index(state), 2)
    if leverage >= threshold:
        tier = "alert"
    elif leverage >= WATCH_THRESHOLD:
        tier = "watch"
    else:
        tier = "quiet"
    return Assessment(leverage=leverage, tier=tier, reasons=_reasons(state))
